### PR TITLE
master: Upgrading Powertool to version 1.10.1 for Log4j version upgrade

### PR DESCRIPTION
**Pull request by poprahul**
Remote for awslabs-master

### CODE REVIEW

**Review by pankajagrawal16 — CHANGES_REQUESTED** [review]
It should be bumped to a bug fix version as in 1.10.1

**Comment by poprahul** [comment]
> It should be bumped to a bug fix version as in 1.10.1

Hi Pankaj, I discussed this with Mark offline, and he mentioned it should be 1.11.0

**Comment by pankajagrawal16** [comment]
> > It should be bumped to a bug fix version as in 1.10.1
> 
> 
> 
> Hi Pankaj, I discussed this with Mark offline, and he mentioned it should be 1.11.0

I am not sure if i agree if it should be a minor version upgrade when log4j itself has bug fix version cc @msailes

**Comment by msailes** [comment]
1.10.1 it is.

**Comment by poprahul** [comment]
> 1.10.1 it is.

Made changes to reflect 1.10.1. Please review

**Review by pankajagrawal16 — COMMENTED** [review]
One suggestion

**Review by msailes — DISMISSED** [review]
👍🏻

**Pull request merged**
