### PR TITLE
feat: remove deprecated attributes on Tracing annotation

### PR DESCRIPTION
**Pull request by pankajagrawal16**
**Issue #, if available:**

## Description of changes:

**Checklist**

 

* [x] [Meet tenets criteria](https://awslabs.github.io/aws-lambda-powertools-java/#tenets)
* [x] Update tests
* [x] Update docs
* [x] PR title follows [conventional commit semantics]()

## Breaking change checklist

**RFC issue #**:

* [ ] Migration process documented
* [ ] Implement warnings (if it can live side by side)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by msailes** [comment]
So this has been deprecated since Jan, would the plan be to document the migration in the release notes?

Which part of the version number do you think we should change?

**Comment by pankajagrawal16** [comment]
> So this has been deprecated since Jan, would the plan be to document the migration in the release notes?
> 
> Which part of the version number do you think we should change?

Yes, the plan is to document it as part of the release note and change log.  I am still considering a minor version increase since this should cause compile time issue for users

**Comment by pankajagrawal16** [comment]
@msailes Have a look and see if you agree :)

**Review by msailes — APPROVED** [review]
👍

**Pull request merged**
