### PR TITLE
chore: gradle example

### PR DESCRIPTION
**Pull request by pankajagrawal16**
**Issue #, if available:**

## Description of changes:

**Checklist**

 

* [x] [Meet tenets criteria](https://awslabs.github.io/aws-lambda-powertools-java/#tenets)
* [x] Update tests
* [x] Update docs
* [x] PR title follows [conventional commit semantics]()

## Breaking change checklist

**RFC issue #**:

* [ ] Migration process documented
* [ ] Implement warnings (if it can live side by side)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by pankajagrawal16** [comment]
So i will be externalizing the limitations of gradle setup as of today as part of issue template here https://github.com/awslabs/aws-lambda-powertools-java/issues/146.

Basically setup works with gradle5.x and not with 6.x coz of issue with the Aspect4j plugin.

**Comment by am29d** [comment]
Besides two minor points its LGTM: 
* the .jar file for the gradle wrapper is missing, was probably ignored by `.gitignore`.
* should we put the merge `example` and `gradle-example`. I thought maybe having one folder with both build files would reduce the maintenance.

**Comment by pankajagrawal16** [comment]
> Besides two minor points its LGTM:
> 
> * the .jar file for the gradle wrapper is missing, was probably ignored by `.gitignore`.
> * should we merge `example` and `gradle-example`? I thought maybe having one folder with both build files would reduce the maintenance.

Good catch. Pushed the wrapper jar now. 👍 

Could you elaborate on the other point? I am not sure if I understand.  🙈

**Comment by am29d** [comment]
> > Besides two minor points its LGTM:
> > 
> > * the .jar file for the gradle wrapper is missing, was probably ignored by `.gitignore`.
> > * should we merge `example` and `gradle-example`? I thought maybe having one folder with both build files would reduce the maintenance.
> 
> Good catch. Pushed the wrapper jar now. 👍
> 
> Could you elaborate on the other point? I am not sure if I understand. 🙈

I am sorry I was looking into a wrong branch :( 

LGTM

**Review by am29d — APPROVED** [review]

**Pull request merged**
